// Ink-on-paper palette: cream page, navy ink, coral accent,
// leaf green for success, brick red for miss.
const styles = {
  page: {
    minHeight: "100vh",
    background: "#F4F1EA",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Verdana', 'Trebuchet MS', sans-serif",
    padding: 16,
  },
  frame: {
    width: "100%",
    maxWidth: 960,
    minHeight: 720,
    background: "#FFF8EC",
    borderRadius: 24,
    boxShadow: "0 20px 60px rgba(22,33,58,0.18)",
    border: "1px solid #E7DFCD",
    overflow: "hidden",
    position: "relative",
  },
  // ---- Title / Game Over / Pause shared layout ----
  titleWrap: {
    minHeight: 720,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    padding: "40px 32px",
  },
  eyebrow: {
    fontSize: 12,
    letterSpacing: "0.18em",
    color: "#8A7F68",
    fontWeight: 700,
    marginBottom: 12,
  },
  title: {
    fontSize: 44,
    fontWeight: 900,
    color: "#16213A",
    margin: 0,
    lineHeight: 1.05,
  },
  tagline: {
    color: "#5B5546",
    fontSize: 15,
    marginTop: 14,
    maxWidth: 380,
    lineHeight: 1.5,
  },
  // ---- How-to instructions ----
  howTo: {
    marginTop: 26,
    width: "100%",
    maxWidth: 360,
    textAlign: "left",
  },
  howToRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 14,
    color: "#16213A",
    marginBottom: 8,
  },
  howToNum: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    background: "#16213A",
    color: "#FFF8EC",
    fontSize: 11,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  // ---- Difficulty picker ----
  difficultySection: {
    marginTop: 28,
    width: "100%",
    maxWidth: 360,
  },
  difficultyLabel: {
    fontSize: 11,
    letterSpacing: "0.14em",
    color: "#8A7F68",
    fontWeight: 700,
    marginBottom: 10,
    textAlign: "left",
  },
  difficultyGrid: {
    display: "flex",
    gap: 12,
  },
  difficultyCard: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 12,
    border: "2px solid transparent",
    background: "#F4F1EA",
    cursor: "pointer",
    textAlign: "left",
    transition: "border-color 0.15s, background 0.15s",
  },
  difficultyCardSelected: {
    borderColor: "#16213A",
    background: "#EDE8DF",
  },
  difficultyCardTitle: {
    fontSize: 14,
    fontWeight: 800,
    color: "#16213A",
    display: "block",
  },
  difficultyCardDesc: {
    fontSize: 12,
    color: "#8A7F68",
    marginTop: 2,
    display: "block",
  },
  // ---- Shared buttons ----
  bigButton: {
    marginTop: 24,
    background: "#E8552E",
    color: "#FFF8EC",
    border: "none",
    borderRadius: 14,
    padding: "14px 32px",
    fontSize: 16,
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: "0 8px 20px rgba(232,85,46,0.35)",
    width: "100%",
    maxWidth: 320,
  },
  secondaryButton: {
    marginTop: 12,
    background: "transparent",
    color: "#16213A",
    border: "2px solid #16213A",
    borderRadius: 14,
    padding: "12px 32px",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    width: "100%",
    maxWidth: 320,
  },
  // ---- Play screen ----
  playWrap: {
    minHeight: 720,
    display: "flex",
    flexDirection: "column",
  },
  hud: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 20px 8px",
    gap: 8,
  },
  hudStats: {
    display: "flex",
    gap: 24,
    alignItems: "center",
  },
  hudItem: { textAlign: "center" },
  hudLabel: {
    fontSize: 10,
    letterSpacing: "0.12em",
    color: "#8A7F68",
    fontWeight: 700,
  },
  hudValue: {
    fontSize: 18,
    fontWeight: 800,
    color: "#16213A",
    letterSpacing: 2,
  },
  hudActions: {
    display: "flex",
    gap: 8,
    alignItems: "center",
  },
  hudIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    border: "2px solid #16213A",
    background: "#FFF8EC",
    color: "#16213A",
    fontSize: 16,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  promptBar: {
    margin: "4px 20px 12px",
    background: "#16213A",
    borderRadius: 12,
    padding: "12px 16px",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  promptKind: {
    fontSize: 10,
    letterSpacing: "0.14em",
    color: "#E8552E",
    fontWeight: 800,
  },
  promptText: {
    color: "#FFF8EC",
    fontSize: 17,
    fontWeight: 700,
  },
  sky: {
    position: "relative",
    flex: 1,
    margin: "0 12px 12px",
    background:
      "linear-gradient(180deg, #DCEBEF 0%, #EFEAD9 70%, #E7DFCD 100%)",
    borderRadius: 16,
    overflow: "hidden",
    minHeight: 500,
  },
  fallingWord: {
    position: "absolute",
    transform: "translateX(-50%)",
    border: "2px solid #16213A",
    borderRadius: 10,
    padding: "8px 14px",
    fontSize: 16,
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: "0 4px 0 rgba(22,33,58,0.25)",
    transition: "background 0.15s, color 0.15s",
    minWidth: 64,
    whiteSpace: "nowrap",
  },
  groundLine: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 4,
    background: "#16213A",
  },
  // ---- Countdown overlay ----
  countdownOverlay: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(244, 241, 234, 0.55)",
    borderRadius: 16,
    zIndex: 10,
    pointerEvents: "none",
  },
  countdownNum: {
    fontSize: 96,
    fontWeight: 900,
    color: "#16213A",
    lineHeight: 1,
    textShadow: "0 4px 0 rgba(22,33,58,0.15)",
    letterSpacing: "-2px",
  },
  // ---- Pause screen stats ----
  pauseStats: {
    display: "flex",
    gap: 40,
    marginTop: 28,
    marginBottom: 4,
  },
  pauseStatItem: {
    textAlign: "center",
  },
  pauseStatLabel: {
    fontSize: 11,
    letterSpacing: "0.14em",
    color: "#8A7F68",
    fontWeight: 700,
    marginBottom: 4,
  },
  pauseStatValue: {
    fontSize: 32,
    fontWeight: 900,
    color: "#16213A",
  },
};

export default styles;
